### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by 948427064** [Orenoid/deprecated_account_bot#13]
我怎么看

**Comment by Orenoid** [comment]
不好意思，刚看到这个 issue ……
这个项目主要是我写来自己用的，是我新手期写的项目，项目架构设计不太好，不建议使用或者参考代码。
我最近刚开始用 Go 重写这个项目，感兴趣可以关注下，也欢迎提需求。
https://github.com/Orenoid/Account-Bot
